more like Version Control Unit
RIT-EVT/VCU pull request #1
Opened 2024-02-20 00:21 UTC by aclowmclaughlin

Initial setup for the repository. Updated submodules, integrated ReadTheDocs (maybe, that's still sorta not working, I think maybe this branch needs to be merged for it to work), and updated the readme.

2024-02-20 00:31 UTC, ActuallyTaylor approved these changes

2024-02-20 01:15 UTC, aclowmclaughlin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Set up the VCU Project](https://trello.com/c/MJ8X3eoG/232-set-up-the-vcu-project)

2024-02-21 22:22 UTC, mjmagee991 requested changes
A couple description details, but looks pretty good

2024-02-21 22:22 UTC, mjmagee991 commented on README.md
> +motor controller, and will control the LVSS in order to turn the bike on and off.
```suggestion
motor controller. It will also command the LVSS in order to the bike through its boot-up and shutdown procedures.
```

2024-02-21 22:22 UTC, mjmagee991 commented on README.md
> +control system. It will primarily take input from the Handlebar Interface Board and communicate those inputs to the
```suggestion
It will primarily take input from the Handlebar Interface Board and use them to decide a torque to send to the 
```

2024-02-21 22:22 UTC, mjmagee991 commented on README.md
> +order and tell them what to do. It will also be responsible for running Simulink models for the TMU and the traction
```suggestion
order and tell them what to do. It will run a Simulink model to handle all the application-level logic for controlling the bike. 
```

2024-02-24 15:03 UTC, mjmagee991 approved these changes
Good start!

2024-02-24 15:04 UTC, merged